// نصوص البوت الافتراضية (عربي وإنجليزي). المنشأة تقدر تعدّل أي مفتاح من لوحتها (settings.texts)
export type Lang = "ar" | "en";

export const TEXTS: Record<Lang, Record<string, string>> = {
  ar: {
    welcome: "هلا وسهلا في {biz} 👋\nكيف نقدر نخدمك؟",
    btn_book: "احجز من هنا",
    btn_orders: "طلباتي",
    btn_lang: "English",
    ask_service: "وش الخدمة اللي تحتاجها؟",
    btn_services: "الخدمات",
    ask_location: "أرسل موقعك من زر «إرسال الموقع» 📍\nأو الصق رابط الموقع من قوقل ماب.",
    bad_location: "ما قدرت أقرأ الموقع 🙏\nأرسله من زر «إرسال الموقع» أو الصق رابط قوقل ماب.",
    out_of_area: "نعتذر، موقعك خارج نطاق خدمتنا حاليًا.\nنغطي: {cities}",
    btn_other_location: "موقع ثاني",
    btn_contact: "تواصل معنا",
    ask_day: "اختر اليوم المناسب 📅",
    btn_days: "الأيام",
    day_desc: "{n} مواعيد متاحة",
    day_desc_many: "{n} موعد متاح",
    day_desc_two: "موعدين متاحين",
    day_desc_one: "موعد واحد متاح",
    no_days: "ما فيه مواعيد متاحة في الأيام الجاية.\nتقدر تتواصل معنا وننسق لك موعد.",
    ask_time: "اختر الوقت المناسب ليوم {day} ⏰",
    btn_times: "الأوقات",
    more_times: "أوقات أكثر",
    slot_taken: "هذا الوقت انحجز قبل شوي، اختر وقت ثاني 🙏",
    confirmed: "تم تأكيد طلبك ✅\nرقم الطلب: {no}\n📅 {day}\n⏰ {time}{city_line}{price_line}\n\n{tail}",
    city_line: "\n📍 {city}",
    price_after: "السعر يتحدد بعد الزيارة",
    price_line: "\n💰 {price}",
    price_fixed: "{price} ريال",
    confirmed_tail: "بيوصلك تذكير قبل الموعد، وتنبيه لما يكون الموظف في الطريق.",
    btn_new_order: "طلب جديد",
    no_orders: "ما عندك طلبات حالية.",
    my_orders: "طلباتك الحالية 👇",
    order_info: "طلب رقم {no}\n📅 {day}\n⏰ {time}\nالحالة: {status}",
    btn_change_time: "تغيير الموعد",
    btn_cancel_order: "إلغاء الطلب",
    btn_back: "رجوع",
    confirm_cancel: "متأكد تبي تلغي طلب رقم {no}؟",
    btn_yes_cancel: "نعم، ألغِ الطلب",
    btn_no: "لا",
    cancelled: "تم إلغاء طلبك رقم {no}.",
    kept: "تمام، طلبك رقم {no} باقي على موعده 👍",
    rescheduled: "تم تغيير موعد طلبك رقم {no} ✅\n📅 {day}\n⏰ {time}",
    order_locked: "طلبك رقم {no} قيد التنفيذ الحين، وما نقدر نعدله من هنا.",
    reminder: "تذكير بموعدك ⏰\nطلب رقم {no}\n📅 {day}\n⏰ {time}",
    on_the_way: "{staff} في الطريق لك 🚗\nطلب رقم {no}",
    arrived: "وصل {staff} لموقعك 📍\nطلب رقم {no}",
    invoice: "فاتورة طلبك رقم {no} 🧾\nالإجمالي: {total} ريال",
    invoice_pay: "تقدر تدفع بمدى أو أبل باي أو البطاقة من الزر تحت.",
    btn_pay: "ادفع الحين",
    paid: "وصلنا دفعك ✅\nشكرًا لك، طلب رقم {no} مكتمل.",
    done: "شكرًا لك، طلب رقم {no} مكتمل ✅",
    cancelled_by_biz: "نعتذر، تم إلغاء طلبك رقم {no}.{reason}",
    rescheduled_by_biz: "تم تغيير موعد طلبك رقم {no}\n📅 {day}\n⏰ {time}",
    handoff: "وصلت رسالتك لفريق {biz} 🙏\nبيرد عليك واحد منهم بأقرب وقت.",
    handoff_complaint: "نعتذر لك 🙏 وصلت ملاحظتك لفريق {biz}، وبيتواصلون معك بأسرع وقت.",
    prices: "أسعارنا:\n{list}",
    prices_after: "السعر يتحدد بعد ما نشوف الشغل في الزيارة.",
    hours: "أوقات العمل:\n{list}",
    areas: "نغطي: {cities}",
    thanks: "العفو، في الخدمة دايم 🌷",
    pick_from_list: "اختر من القائمة 👇",
    closed: "مغلق",
    st_confirmed: "مؤكد",
    st_on_the_way: "الموظف في الطريق",
    st_arrived: "الموظف وصل",
    st_invoiced: "بانتظار الدفع",
    st_done: "مكتمل",
    st_cancelled: "ملغي",
    today: "اليوم",
    tomorrow: "بكرة",
    owner_new_order: "طلب جديد رقم {no} 🔔\n{customer}\n📅 {day} ⏰ {time}{city_line}",
    owner_handoff: "عميل يحتاج رد 💬\n{customer}: {text}",
    ask_branch: "اختر الفرع اللي يناسبك 📍",
    btn_branches: "الفروع",
    place_shop: "\n📍 {branch}{maps}",
    place_online: "\n💻 {online}",
    online_default: "أونلاين، ويوصلك رابط الجلسة قبل الموعد",
    tail_shop: "بيوصلك تذكير قبل الموعد، ونتشرف بزيارتك 🌷",
    tail_online: "بيوصلك تذكير قبل الموعد مع رابط الجلسة.",
    pay_to_confirm: "باقي خطوة وحدة ✅\nادفع {amount} ريال لتأكيد حجزك:\n📅 {day}\n⏰ {time}{city_line}\n\nالموعد محجوز لك {hold} دقيقة.",
    btn_pay_confirm: "ادفع وأكّد الحجز",
    prepay_label: "تأكيد الحجز",
    prepaid_confirmed: "وصلنا دفعك وتأكد حجزك ✅\nرقم الطلب: {no}\n📅 {day}\n⏰ {time}{city_line}\n\n{tail}",
    hold_expired: "انتهت مهلة الدفع للموعد {day} {time}، وانفك الحجز.\nتقدر تحجز من جديد متى ما حبيت.",
    st_pending_payment: "بانتظار الدفع",
    loc_shop: "مواقعنا 📍\n{list}",
    loc_online: "خدماتنا أونلاين، ما تحتاج تجينا 💻\nاحجز موعدك ويوصلك رابط الجلسة.",
    loc_visit: "نجيك لين موقعك 🚗\nنغطي: {cities}",
    pay_before: "الدفع وقت الحجز برابط آمن: مدى، أبل باي، أو البطاقة 💳",
    pay_after: "تدفع بعد الخدمة: نرسل لك الفاتورة ورابط دفع (مدى، أبل باي، البطاقة)، أو كاش وشبكة 💳",
    pay_none: "الدفع بعد الخدمة: كاش أو شبكة 💳",
    services_list: "خدماتنا:\n{list}",
  },
  en: {
    welcome: "Welcome to {biz} 👋\nHow can we help you?",
    btn_book: "Book now",
    btn_orders: "My orders",
    btn_lang: "عربي",
    ask_service: "Which service do you need?",
    btn_services: "Services",
    ask_location: "Send your location using the «Send location» button 📍\nor paste a Google Maps link.",
    bad_location: "We couldn't read that location 🙏\nUse the «Send location» button or paste a Google Maps link.",
    out_of_area: "Sorry, your location is outside our service area.\nWe cover: {cities}",
    btn_other_location: "Another location",
    btn_contact: "Contact us",
    ask_day: "Pick a day 📅",
    btn_days: "Days",
    day_desc: "{n} times available",
    day_desc_many: "{n} times available",
    day_desc_two: "2 times available",
    day_desc_one: "1 time available",
    no_days: "No times are available in the coming days.\nContact us and we'll arrange one.",
    ask_time: "Pick a time for {day} ⏰",
    btn_times: "Times",
    more_times: "More times",
    slot_taken: "That time was just taken, please pick another 🙏",
    confirmed: "Your order is confirmed ✅\nOrder number: #{no}\n📅 {day}\n⏰ {time}{city_line}{price_line}\n\n{tail}",
    city_line: "\n📍 {city}",
    price_after: "Price is set after the visit",
    price_line: "\n💰 {price}",
    price_fixed: "SAR {price}",
    confirmed_tail: "You'll get a reminder before your appointment, and a message when our staff is on the way.",
    btn_new_order: "New order",
    no_orders: "You have no current orders.",
    my_orders: "Your current orders 👇",
    order_info: "Order #{no}\n📅 {day}\n⏰ {time}\nStatus: {status}",
    btn_change_time: "Change time",
    btn_cancel_order: "Cancel order",
    btn_back: "Back",
    confirm_cancel: "Cancel order #{no}?",
    btn_yes_cancel: "Yes, cancel it",
    btn_no: "No",
    cancelled: "Order #{no} has been cancelled.",
    kept: "Great, order #{no} stays as booked 👍",
    rescheduled: "Order #{no} has a new time ✅\n📅 {day}\n⏰ {time}",
    order_locked: "Order #{no} is in progress and can't be changed here.",
    reminder: "Appointment reminder ⏰\nOrder #{no}\n📅 {day}\n⏰ {time}",
    on_the_way: "{staff} is on the way 🚗\nOrder #{no}",
    arrived: "{staff} has arrived 📍\nOrder #{no}",
    invoice: "Invoice for order #{no} 🧾\nTotal: SAR {total}",
    invoice_pay: "Pay with mada, Apple Pay or card using the button below.",
    btn_pay: "Pay now",
    paid: "Payment received ✅\nThank you, order #{no} is complete.",
    done: "Thank you, order #{no} is complete ✅",
    cancelled_by_biz: "Sorry, order #{no} has been cancelled.{reason}",
    rescheduled_by_biz: "Order #{no} has a new time\n📅 {day}\n⏰ {time}",
    handoff: "Your message reached the {biz} team 🙏\nSomeone will reply shortly.",
    handoff_complaint: "We're sorry 🙏 The {biz} team got your note and will contact you soon.",
    prices: "Our prices:\n{list}",
    prices_after: "The price is set after we see the job during the visit.",
    hours: "Working hours:\n{list}",
    areas: "We cover: {cities}",
    thanks: "You're welcome 🌷",
    pick_from_list: "Please pick from the list 👇",
    closed: "Closed",
    st_confirmed: "Confirmed",
    st_on_the_way: "Staff on the way",
    st_arrived: "Staff arrived",
    st_invoiced: "Awaiting payment",
    st_done: "Complete",
    st_cancelled: "Cancelled",
    today: "Today",
    tomorrow: "Tomorrow",
    owner_new_order: "New order #{no} 🔔\n{customer}\n📅 {day} ⏰ {time}{city_line}",
    owner_handoff: "Customer needs a reply 💬\n{customer}: {text}",
    ask_branch: "Pick the branch that suits you 📍",
    btn_branches: "Branches",
    place_shop: "\n📍 {branch}{maps}",
    place_online: "\n💻 {online}",
    online_default: "Online, the session link reaches you before the appointment",
    tail_shop: "You'll get a reminder before your appointment. See you soon 🌷",
    tail_online: "You'll get a reminder before your appointment with the session link.",
    pay_to_confirm: "One last step ✅\nPay SAR {amount} to confirm your booking:\n📅 {day}\n⏰ {time}{city_line}\n\nThe slot is held for you for {hold} minutes.",
    btn_pay_confirm: "Pay and confirm",
    prepay_label: "Booking confirmation",
    prepaid_confirmed: "Payment received, your booking is confirmed ✅\nOrder number: #{no}\n📅 {day}\n⏰ {time}{city_line}\n\n{tail}",
    hold_expired: "The payment time for {day} {time} ended and the slot was released.\nYou can book again anytime.",
    st_pending_payment: "Awaiting payment",
    loc_shop: "Our locations 📍\n{list}",
    loc_online: "Our services are online, no visit needed 💻\nBook a time and the session link reaches you.",
    loc_visit: "We come to your location 🚗\nWe cover: {cities}",
    pay_before: "You pay when booking with a secure link: mada, Apple Pay, or card 💳",
    pay_after: "You pay after the service: we send the invoice with a payment link (mada, Apple Pay, card), or cash 💳",
    pay_none: "Payment after the service: cash or card 💳",
    services_list: "Our services:\n{list}",
  },
};

// أساليب الردود (العربي): ودّي (الافتراضي)، رسمي، مختصر. المنشأة تختار الأسلوب وتعدّل فوقه أي نص
export const TONES: Record<string, Record<string, string>> = {
  formal: {
    welcome: "مرحبًا بكم في {biz}.\nكيف يمكننا خدمتكم؟",
    btn_book: "احجز موعدًا",
    ask_service: "يرجى اختيار الخدمة المطلوبة.",
    ask_location: "يرجى إرسال موقعكم عبر زر «إرسال الموقع»، أو لصق رابط الموقع من خرائط قوقل.",
    bad_location: "تعذّرت قراءة الموقع. يرجى إرساله عبر زر «إرسال الموقع» أو لصق رابط خرائط قوقل.",
    out_of_area: "نعتذر، موقعكم خارج نطاق خدمتنا حاليًا.\nنغطي: {cities}",
    ask_branch: "يرجى اختيار الفرع المناسب.",
    ask_day: "يرجى اختيار اليوم المناسب.",
    ask_time: "يرجى اختيار الوقت المناسب ليوم {day}.",
    slot_taken: "نعتذر، تم حجز هذا الوقت للتو. يرجى اختيار وقت آخر.",
    confirmed: "تم تأكيد طلبكم.\nرقم الطلب: {no}\n📅 {day}\n⏰ {time}{city_line}{price_line}\n\n{tail}",
    confirmed_tail: "سيصلكم تذكير قبل الموعد، وإشعار عند توجه الموظف إليكم.",
    tail_shop: "سيصلكم تذكير قبل الموعد. نسعد بزيارتكم.",
    tail_online: "سيصلكم تذكير قبل الموعد مع رابط الجلسة.",
    no_orders: "لا توجد لديكم طلبات حالية.",
    my_orders: "طلباتكم الحالية:",
    reminder: "تذكير بموعدكم\nطلب رقم {no}\n📅 {day}\n⏰ {time}",
    on_the_way: "{staff} في الطريق إليكم.\nطلب رقم {no}",
    paid: "تم استلام الدفعة بنجاح.\nشكرًا لكم، طلب رقم {no} مكتمل.",
    handoff: "تم تحويل رسالتكم إلى فريق {biz}، وسيتم الرد عليكم في أقرب وقت.",
    handoff_complaint: "نعتذر عن ذلك. تم تحويل ملاحظتكم إلى فريق {biz} وسيتم التواصل معكم في أقرب وقت.",
    prices_after: "يُحدَّد السعر بعد معاينة العمل.",
    thanks: "شكرًا لتواصلكم معنا.",
    pay_to_confirm: "لتأكيد الحجز يرجى دفع {amount} ريال:\n📅 {day}\n⏰ {time}{city_line}\n\nالموعد محجوز لكم لمدة {hold} دقيقة.",
    prepaid_confirmed: "تم استلام الدفعة وتأكيد الحجز.\nرقم الطلب: {no}\n📅 {day}\n⏰ {time}{city_line}\n\n{tail}",
    pay_before: "يتم الدفع عند الحجز عبر رابط آمن: مدى، أو أبل باي، أو البطاقة.",
    pay_after: "يتم الدفع بعد الخدمة عبر رابط الفاتورة (مدى، أبل باي، البطاقة) أو نقدًا.",
    pay_none: "يتم الدفع بعد الخدمة نقدًا أو بالبطاقة.",
    loc_online: "خدماتنا تقدّم عن بُعد، ويصلكم رابط الجلسة بعد الحجز.",
  },
  short: {
    welcome: "أهلًا 👋 {biz}",
    btn_book: "احجز",
    ask_service: "الخدمة؟",
    ask_location: "📍 أرسل موقعك (زر الموقع أو رابط قوقل ماب)",
    bad_location: "📍 أرسل الموقع من زر الموقع أو رابط قوقل ماب",
    out_of_area: "خارج نطاقنا. نغطي: {cities}",
    ask_branch: "الفرع؟",
    ask_day: "📅 اليوم؟",
    ask_time: "⏰ الوقت؟ ({day})",
    slot_taken: "الوقت انحجز، اختر غيره",
    confirmed: "✅ تم الحجز · رقم {no}\n📅 {day} ⏰ {time}{city_line}{price_line}",
    no_orders: "ما عندك طلبات",
    my_orders: "طلباتك:",
    reminder: "⏰ تذكير: طلب {no} · {day} {time}",
    on_the_way: "🚗 {staff} في الطريق · طلب {no}",
    paid: "✅ وصلنا دفعك · طلب {no} مكتمل",
    handoff: "وصلت رسالتك للفريق 🙏",
    handoff_complaint: "نعتذر 🙏 وصلت ملاحظتك للفريق",
    prices_after: "السعر بعد المعاينة",
    thanks: "العفو 🌷",
    pay_to_confirm: "ادفع {amount} ريال لتأكيد حجزك\n📅 {day} ⏰ {time}{city_line}\nمحجوز لك {hold} دقيقة",
    prepaid_confirmed: "✅ وصلنا دفعك وتأكد حجزك · رقم {no}\n📅 {day} ⏰ {time}{city_line}",
  },
};

// المفاتيح اللي تقدر المنشأة تعدّلها من لوحتها (مع وصف عربي)
export const EDITABLE: { key: string; label: string }[] = [
  { key: "welcome", label: "الترحيب" },
  { key: "ask_location", label: "طلب الموقع" },
  { key: "out_of_area", label: "خارج النطاق" },
  { key: "ask_day", label: "اختيار اليوم" },
  { key: "confirmed_tail", label: "سطر بعد التأكيد" },
  { key: "reminder", label: "التذكير" },
  { key: "on_the_way", label: "في الطريق" },
  { key: "paid", label: "وصلنا دفعك" },
  { key: "handoff", label: "التحويل للفريق" },
  { key: "handoff_complaint", label: "الرد على الشكوى" },
  { key: "thanks", label: "الرد على الشكر" },
];

export type TextBag = (key: string, vars?: Record<string, unknown>) => string;

export function textsFor(lang: Lang, overrides: any, tone = "friendly"): TextBag {
  const base = (lang === "ar" && TONES[tone]) ? { ...TEXTS.ar, ...TONES[tone] } : (TEXTS[lang] || TEXTS.ar);
  const over = (overrides && typeof overrides === "object" && overrides[lang] && typeof overrides[lang] === "object") ? overrides[lang] : {};
  return (key: string, vars: Record<string, unknown> = {}) => {
    const tpl = (typeof over[key] === "string" && over[key].trim()) ? over[key] : (base[key] ?? TEXTS.ar[key] ?? key);
    return tpl.replace(/\{(\w+)\}/g, (_m: string, k: string) => (vars[k] === undefined || vars[k] === null) ? "" : String(vars[k]));
  };
}
